"""
Word document builder for Multi-Agent Studio.

Takes the final pipeline state and produces a .docx file as bytes.
The bytes are returned directly to Streamlit's download button —
no file is written to disk.

Handles markdown-style headings (## and ###) and bold markers (**text**)
by converting them to proper Word heading styles and bold runs.
"""

import io
import re
from datetime import date
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def _set_normal_style(doc: Document) -> None:
    """Sets base font and margins for the document."""
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)

    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1.2)
        section.right_margin = Inches(1.2)


def _add_bold_runs(paragraph, text: str) -> None:
    """
    Adds text to a paragraph, converting **bold** markers to bold runs.
    Plain text outside ** ** is added as a normal run.
    """
    parts = re.split(r"(\*\*.*?\*\*)", text)
    for part in parts:
        if part.startswith("**") and part.endswith("**"):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        else:
            paragraph.add_run(part)


def _add_markdown_content(doc: Document, text: str) -> None:
    """
    Parses markdown-style text and adds it to the document.
    Converts:
        ## Heading  →  Word Heading 1
        ### Heading →  Word Heading 2
        **bold**    →  bold run
        blank line  →  paragraph break
    """
    for line in text.split("\n"):
        stripped = line.strip()

        if stripped.startswith("### "):
            heading = doc.add_heading(stripped[4:], level=2)
            heading.style.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)

        elif stripped.startswith("## "):
            heading = doc.add_heading(stripped[3:], level=1)
            heading.style.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)

        elif stripped == "":
            doc.add_paragraph("")

        else:
            para = doc.add_paragraph()
            _add_bold_runs(para, stripped)


def build_research_doc(state: dict) -> bytes:
    """
    Builds a Word document from the completed research pipeline state.

    Args:
        state: the final ResearchState dict after all agents have run.

    Returns:
        bytes: the .docx file contents, ready for st.download_button.
    """
    doc = Document()
    _set_normal_style(doc)

    topic = state.get("topic", "Research Report")
    final_text = state.get("final", state.get("draft", "No output generated."))
    sources = state.get("sources", [])
    model_used = state.get("model_used", "unknown")
    today = date.today().strftime("%B %d, %Y")

    # ── Title block ──────────────────────────────────────────────────────────
    title_para = doc.add_heading(topic, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.LEFT

    meta = doc.add_paragraph(f"Research Assistant  |  {today}")
    meta.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)
    meta.runs[0].font.size = Pt(9)

    doc.add_paragraph("")  # spacer

    # ── Main content ─────────────────────────────────────────────────────────
    _add_markdown_content(doc, final_text)

    # ── Sources ──────────────────────────────────────────────────────────────
    if sources:
        doc.add_paragraph("")
        doc.add_heading("Sources", level=1)
        for i, url in enumerate(sources, 1):
            doc.add_paragraph(f"{i}. {url}", style="List Number")

    # ── Footer ───────────────────────────────────────────────────────────────
    doc.add_paragraph("")
    footer_para = doc.add_paragraph(
        f"Generated by Multi-Agent Studio — Research Assistant  |  Model: {model_used}  |  {today}\n"
        "AI-generated output. Review before use."
    )
    footer_para.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)
    footer_para.runs[0].font.size = Pt(8)

    # ── Return as bytes ──────────────────────────────────────────────────────
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.read()
